# Generated by Django 5.1.4 on 2026-01-05 04:24

import common.utils.time
import django.db.models.deletion
import django.utils.timezone
import secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('device_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('device_fingerprint', models.CharField(db_index=True, max_length=512)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('os_family', models.CharField(max_length=128)),
                ('device_type', models.CharField(max_length=128)),
                ('platform', models.CharField(blank=True, max_length=64)),
                ('gpu_vendor', models.CharField(blank=True, max_length=255)),
                ('hardware_concurrency', models.IntegerField(blank=True, null=True)),
                ('device_memory', models.FloatField(blank=True, null=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=32)),
                ('browser_timezone', models.CharField(blank=True, max_length=64)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('first_seen_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('last_seen_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('access_count', models.PositiveIntegerField(default=1)),
                ('trusted', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(default=common.utils.time.in_24_hours)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(default=secrets.token_urlsafe, max_length=255, unique=True)),
                ('secret_type', models.CharField(choices=[('password_reset', 'Password Reset'), ('email_verification', 'Email Verification'), ('two_factor', 'Two Factor Auth')], default='password_reset', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'secret',
            },
        ),
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('browser_family', models.CharField(max_length=128)),
                ('user_agent', models.CharField(max_length=512)),
                ('access_count', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('last_seen_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsers', to='account.device')),
            ],
            options={
                'db_table': 'browser',
                'ordering': ['-last_seen_at'],
                'unique_together': {('device', 'browser_family')},
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('access_count', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('last_seen_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('blocked', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='account.device')),
            ],
            options={
                'db_table': 'ip_address',
                'ordering': ['-last_seen_at'],
                'unique_together': {('device', 'ip_address')},
            },
        ),
    ]
