# Generated by Django 5.1.4 on 2025-12-10 20:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_email_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('device_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('device_fingerprint', models.CharField(db_index=True, max_length=512)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('os_family', models.CharField(max_length=128)),
                ('device_type', models.CharField(max_length=128)),
                ('platform', models.CharField(blank=True, max_length=64)),
                ('hardware_concurrency', models.IntegerField(blank=True, null=True)),
                ('device_memory', models.IntegerField(blank=True, null=True)),
                ('gpu_vendor', models.CharField(blank=True, max_length=255)),
                ('screen_resolution', models.CharField(blank=True, max_length=32)),
                ('browser_timezone', models.CharField(blank=True, max_length=64)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('first_seen_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('last_seen_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('access_count', models.PositiveIntegerField(default=1)),
                ('trusted', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('browser_family', models.CharField(max_length=128)),
                ('user_agent', models.CharField(max_length=512)),
                ('access_count', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('last_seen_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsers', to='account.device')),
            ],
            options={
                'db_table': 'browser',
                'ordering': ['-last_seen_at'],
                'unique_together': {('device', 'browser_family')},
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('access_count', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('last_seen_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('blocked', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='account.device')),
            ],
            options={
                'db_table': 'ip_address',
                'ordering': ['-last_seen_at'],
                'unique_together': {('device', 'ip_address')},
            },
        ),
    ]
