# Generated by Django 5.1.4 on 2025-12-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_mfa_enabled_device_browser_ipaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_memory',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
