# Generated by Django 5.1.4 on 2026-01-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='germination',
            field=models.CharField(blank=True, choices=[('warm', 'Warm Soil'), ('cool', 'Cool Soil'), ('boil', 'Boil'), ('cold', 'Cold Stratification'), ('scarify', 'Scarify'), ('surface', 'Surface Sowing')], max_length=20),
        ),
        migrations.AddField(
            model_name='plant',
            name='stratification',
            field=models.IntegerField(blank=True, help_text='Stratification time in days. (If applicable)', null=True),
        ),
    ]
